DROP TABLE IF EXISTS `fields_order`;
CREATE TABLE `fields_order` (
  `field` text NOT NULL,
  `fieldDisplayName` text,
  `display_order` integer,
  `category` char(128),
  `activityType` char(128)
);

INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('BeginLatitude','Beginnning Latitude',-1,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('BeginLongitude','Beginning Longitude',-1,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('BeginPowerTwentyMinutesDistance','BeginPowerTwentyMinutesDistance','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('BeginPowerTwentyMinutesTime','BeginPowerTwentyMinutesTime','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('BeginPowerTwentyMinutesTimerTime','BeginPowerTwentyMinutesTimerTime','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('DirectLactateThresholdHeartRate','Lactate Threshold',50,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('DirectLactateThresholdSpeed','Lactate Speed',60,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('DirectVO2Max','DirectVO2Max',10,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('DirectVO2MaxCycling','VO2 Max',300,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('EndLatitude','EndLatitude',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('EndLongitude','EndLongitude',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('EndPowerTwentyMinutesDistance','EndPowerTwentyMinutesDistance','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('EndPowerTwentyMinutesTime','EndPowerTwentyMinutesTime','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('EndPowerTwentyMinutesTimerTime','EndPowerTwentyMinutesTimerTime','<null>','power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GainCorrectedElevation','GainCorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GainElevation','Elevation Gain',1,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GainUncorrectedElevation','GainUncorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GoalSumDistance',NULL,NULL,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GoalSumDuration',NULL,NULL,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GoalSumEnergy',NULL,NULL,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('GoalSumStep',NULL,NULL,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('LossCorrectedElevation','LossCorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('LossElevation','Elevation Loss',2,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('LossUncorrectedElevation','LossUncorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxAirTemperature','Max Temperature',3,'temperature',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxBikeCadence','Max Bike Cadence',2,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxCorrectedElevation','MaxCorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxDoubleCadence','Max Run Cadence',0,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxElevation','Max Elevation',3,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxFractionalCadence','Max Run Cadence',0,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxHeartRate','Max HR',2,'heartrate',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxPace','Best Pace',3,'pace',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxPower','MaxPower',20,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxPowerTwentyMinutes','Max Avg Power (20 min)',4,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxRunCadence','Max Run Cadence',2,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxSpeed','Max Speed',3,'speed',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxSwimCadence','Max Swim Cadence',2,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxUncorrectedElevation','MaxUncorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinAirTemperature','Min Temperature',2,'temperature',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinBikeCadence','MinBikeCadence',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinCorrectedElevation','MinCorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinEfficiency','Best Efficiency',7,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinElevation','Min Elevation',4,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinHeartRate','MinHeartRate',10,'heartrate',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinPower','MinPower',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinRunCadence','MinRunCadence',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinSpeed','Min Speed',-1,'speed',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinStrokes','Min Strokes',4,'swim',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinSwolf','Best SWOLF',6,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinUncorrectedElevation','MinUncorrectedElevation',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDistance','Distance',1,'distance',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDistanceLightlyActive',NULL,10,'distance',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDistanceModeratelyActive',NULL,20,'distance',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDistanceVeryActive',NULL,30,'distance',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDuration','Time',1,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDurationLightlyActive',NULL,10,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDurationModeratelyActive',NULL,20,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumDurationVeryActive',NULL,30,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumElapsedDuration','Elapsed Time',2,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumEnergy','Calories',1,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumEnergyActive',NULL,20,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumIntensityFactor','Intensity Factor (IF)',6,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumMovingDuration','Moving Time',3,'duration',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumNumActiveLengths','Number of Lengths',-1,'swim',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumNumLengths','Number of Lengths',3,'swim',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumPoolLength','Pool Length',-1,'swim',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumStep','Steps',2,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumStrokes','Total Strokes',2,'dynamics',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumStrokes',NULL,30,'swim','swimming');
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumTotalWork','Work',7,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumTrainingEffect','Training Effect',2,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumTrainingStressScore','Training Stress Score (TSS)',3,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('ThresholdPower','threshold-:-power',10,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanAirTemperature','Avg Temperature',1,'temperature',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanBikeCadence','Avg Bike Cadence',1,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanDoubleCadence','Avg Run Cadence',0,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanEfficiency','Avg Efficiency',4,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanFractionalCadence','Avg Run Cadence',0,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanGroundContactBalanceLeft','Contact Balance',60,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanGroundContactTime','Avg Ground Contact Time',2,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanHeartRate','Avg HR',1,'heartrate',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanLeftBalance','Balance Left (%)',9,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanLeftPedalSmoothness','Pedal Smoothness',210,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanLeftTorqueEffectiveness','Left Torque',200,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanMovingPace','Avg Moving Pace',2,'pace',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanMovingSpeed','Avg Moving Speed',2,'speed',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanNormalizedPower','Normalized Power (NP)',2,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanPace','Avg Pace',1,'pace',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanPower','Avg Power',1,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanRightBalance','Balance Right (%)',8,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanRunCadence','Avg Run Cadence',1,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanSpeed','Avg Speed',1,'speed',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanStrideLength','Avg Stride Length',0,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanStrokes','Avg Strokes',1,'swim',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanSwimCadence','Avg Swim Cadence',1,'cadence',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanSwolf','Avg SWOLF',5,'training',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanVerticalOscillation','Avg Vertical Oscillation',3,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanVerticalRatio','Vertical Ratio',70,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcAscentSpeed','Ascent Speed',70,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcDescentSpeed','Descent Speed',80,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcEnergy','__CalcEnergy',30,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcMaxAscentSpeed','Max Ascent Sp',90,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcMaxDescentSpeed','Max Descent Sp',90,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcMetabolicEfficiency','__CalcMetabolicEfficiency',10,'bike',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcRotationDevelopment','__CalcRotationDevelopment',20,'bike',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcStrideLength','__CalcStrideLength',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__CalcVerticalSpeed','Vertical Speed',60,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthfat_free_mass','__healthfat_free_mass',5,'health',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthfat_mass_weight','__healthfat_mass_weight',2,'health',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthfat_ratio','__healthfat_ratio',3,'health',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthheart_rate',NULL,10,'health',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthnone','__healthnone',0,'ignore',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('__healthweight','__healthweigh',1,'health',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('backhands','backhands',1,'backhands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('backhands_flat','backhands_flat',10,'backhands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('backhands_lifted','backhands_lifted',20,'backhands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('backhands_sliced','backhands_sliced',30,'backhands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('first_serves','first_serves',10,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('first_serves_effect','first_serves_effect',12,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('first_serves_flat','first_serves_flat',14,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('forehands','forehands',1,'forehands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('forehands_flat','forehands_flat',10,'forehands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('forehands_lifted','forehands_lifted',20,'forehands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('forehands_sliced','forehands_sliced',30,'forehands',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('heatmap_all_center','Precision Center',150,'precision',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('heatmap_backhands_center','Precision Backhands',170,'precision',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('heatmap_forehands_center','Precision Forehand',160,'precision',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('heatmap_serves_center','Precision Serves',180,'precision',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('heatmap_smash_center','Precision Smash',190,'precision',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('second_serves','second_serves',20,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('second_serves_effect','second_serves_effect',22,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('second_serves_flat','second_serves_flat',24,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('serves','serves',1,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('serves_effect','serves_effect',2,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('serves_flat','serves_flat',3,'serves',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('shots','shots',1,'tennis',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('smash','smash',100,'serves',NULL);

INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxFormPower','MaxFormPower',10,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxGroundContactBalanceLeft','MaxGroundContactBalanceLeft',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxGroundContactTime','MaxGroundContactTime',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxLegSpringStiffness','MaxLegSpringStiffness',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxVerticalOscillation','MaxVerticalOscillation',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxVerticalRatio','MaxVerticalRatio',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MaxVerticalSpeed','MaxVerticalSpeed',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinFormPower','MinFormPower',10,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinGroundContactBalanceLeft','MinGroundContactBalanceLeft',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinGroundContactTime','MinGroundContactTime',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinLegSpringStiffness','MinLegSpringStiffness',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinPace','MinPace',10,'speed',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinVerticalOscillation','MinVerticalOscillation',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('MinVerticalRatio','MinVerticalRatio',10,'run',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumFloorsClimbed','SumFloorsClimbed',10,'elevation'NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('SumFloorsDescended','SumFloorsDescended',10,'elevation',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanFormPower','WeightedMeanFormPower',10,'power',NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanLegSpringStiffness','WeightedMeanLegSpringStiffness',10,'run'NULL);
INSERT INTO `fields_order` (`field`,`fieldDisplayName`,`display_order`,`category`,`activityType`) VALUES ('WeightedMeanVerticalSpeed','WeightedMeanVerticalSpeed',10,'run',NULL);
