FIT_GET_NUMUNIT_FIELD( @"Timestamp", GetTimestamp, FIT_DATE_TIME_INVALID, @"second" );
FIT_GET_NUMUNIT_FIELD( @"PositionLat", GetPositionLat, FIT_SINT32_INVALID, @"semicircle" );
FIT_GET_NUMUNIT_FIELD( @"PositionLong", GetPositionLong, FIT_SINT32_INVALID, @"semicircle" );
FIT_GET_NUMUNIT_FIELD( @"GainElevation", GetAltitude, FIT_FLOAT32_INVALID, @"meter" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanHeartRate", GetHeartRate, FIT_UINT8_INVALID, @"bpm" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanCadence", GetCadence, FIT_UINT8_INVALID, @"rpm" );
FIT_GET_NUMUNIT_FIELD( @"SumDistance", GetDistance, FIT_FLOAT32_INVALID, @"meter" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanSpeed", GetSpeed, FIT_FLOAT32_INVALID, @"mps" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanPower", GetPower, FIT_UINT16_INVALID, @"watt" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumCompressedSpeedDistance", GetNumCompressedSpeedDistance, FIT_UINT8_INVALID, @"watt" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Grade", GetGrade, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Resistance", GetResistance, FIT_UINT8_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"TimeFromCourse", GetTimeFromCourse, FIT_FLOAT32_INVALID, @"second" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"CycleLength", GetCycleLength, FIT_FLOAT32_INVALID, @"meter" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanAirTemperature", GetTemperature, FIT_SINT8_INVALID, @"meter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumSpeed1s", GetNumSpeed1s, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Cycles", GetCycles, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"CompressedAccumulatedPower", GetCompressedAccumulatedPower, FIT_UINT16_INVALID, @"watt" );
// Unknown: FIT_LEFT_RIGHT_BALANCE LeftRightBalance (unit: watt)
//SKIP FIT_GET_NUMUNIT_FIELD( @"GpsAccuracy", GetGpsAccuracy, FIT_UINT8_INVALID, @"meter" );
FIT_GET_NUMUNIT_FIELD( @"VerticalSpeed", GetVerticalSpeed, FIT_FLOAT32_INVALID, @"mps" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Calories", GetCalories, FIT_UINT16_INVALID, @"kilocalorie" );
FIT_GET_NUMUNIT_FIELD( @"WeightedMeanVerticalOscillation", GetVerticalOscillation, FIT_FLOAT32_INVALID, @"millimeter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"StanceTimePercent", GetStanceTimePercent, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"WeightedMeanGroundContactTime", GetStanceTime, FIT_FLOAT32_INVALID, @"millisecond" );
FIT_GET_ENUM_FIELD( @"ActivityType", GetActivityType, FIT_ACTIVITY_TYPE_INVALID, FIT_ACTIVITY_TYPE, @"FIT_ACTIVITY_TYPE" );
FIT_GET_NUMUNIT_FIELD( @"LeftTorqueEffectiveness", GetLeftTorqueEffectiveness, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"RightTorqueEffectiveness", GetRightTorqueEffectiveness, FIT_FLOAT32_INVALID, @"percent" );
FIT_GET_NUMUNIT_FIELD( @"LeftPedalSmoothness", GetLeftPedalSmoothness, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"RightPedalSmoothness", GetRightPedalSmoothness, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"CombinedPedalSmoothness", GetCombinedPedalSmoothness, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Time128", GetTime128, FIT_FLOAT32_INVALID, @"second" );
FIT_GET_ENUM_FIELD( @"StrokeType", GetStrokeType, FIT_STROKE_TYPE_INVALID, FIT_STROKE_TYPE, @"FIT_STROKE_TYPE" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Zone", GetZone, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"BallSpeed", GetBallSpeed, FIT_FLOAT32_INVALID, @"mps" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Cadence256", GetCadence256, FIT_FLOAT32_INVALID, @"rpm" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"FractionalCadence", GetFractionalCadence, FIT_FLOAT32_INVALID, @"rpm" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"TotalHemoglobinConc", GetTotalHemoglobinConc, FIT_FLOAT32_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"TotalHemoglobinConcMin", GetTotalHemoglobinConcMin, FIT_FLOAT32_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"TotalHemoglobinConcMax", GetTotalHemoglobinConcMax, FIT_FLOAT32_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"SaturatedHemoglobinPercent", GetSaturatedHemoglobinPercent, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"SaturatedHemoglobinPercentMin", GetSaturatedHemoglobinPercentMin, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"SaturatedHemoglobinPercentMax", GetSaturatedHemoglobinPercentMax, FIT_FLOAT32_INVALID, @"percent" );
// Unknown: FIT_DEVICE_INDEX DeviceIndex (unit: percent)
//SKIP FIT_GET_NUMUNIT_FIELD( @"LeftPco", GetLeftPco, FIT_SINT8_INVALID, @"millimeter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"RightPco", GetRightPco, FIT_SINT8_INVALID, @"millimeter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumLeftPowerPhase", GetNumLeftPowerPhase, FIT_UINT8_INVALID, @"millimeter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumLeftPowerPhasePeak", GetNumLeftPowerPhasePeak, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumRightPowerPhase", GetNumRightPowerPhase, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NumRightPowerPhasePeak", GetNumRightPowerPhasePeak, FIT_UINT8_INVALID, @"dimensionless" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"EnhancedSpeed", GetEnhancedSpeed, FIT_FLOAT32_INVALID, @"mps" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"EnhancedAltitude", GetEnhancedAltitude, FIT_FLOAT32_INVALID, @"meter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"BatterySoc", GetBatterySoc, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"MotorPower", GetMotorPower, FIT_UINT16_INVALID, @"watt" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"VerticalRatio", GetVerticalRatio, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"StanceTimeBalance", GetStanceTimeBalance, FIT_FLOAT32_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"StepLength", GetStepLength, FIT_FLOAT32_INVALID, @"millimeter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"Depth", GetDepth, FIT_FLOAT32_INVALID, @"meter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"NextStopDepth", GetNextStopDepth, FIT_FLOAT32_INVALID, @"meter" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"CnsLoad", GetCnsLoad, FIT_UINT8_INVALID, @"percent" );
//SKIP FIT_GET_NUMUNIT_FIELD( @"N2Load", GetN2Load, FIT_UINT16_INVALID, @"percent" );
